---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(infer)
library(purrr)
```

```{r}
save_time <- 30 #Years until Retirement
save_add <- 0 #Yearly contributions to retirement savings.
save_add_increase_percent <- 0.03 #Yearly fractional increase in savings

retire_time <- 30 #Amount of time living in retirement.
cost_of_living <- 40000 #How much money from savings are going to be needed each year - in today's dollars?

total_time <- save_time + retire_time

initial_capital <- 315000 #How much money do you have currently saved for retirement?

#Fractional weightings of retirement savings in these asset classes:
large_cap_weight <- 0.4
small_cap_weight <- 0.25
international_weight <- 0.2
bond_weight <- 0.15
CD_weight <- 0

account_for_inflation = T #It would be wise to account for inflation.

reps = 1000 #How many simulations. 1000 is best, but can take a while to calculate.

```
Read In Historical Data
```{r}
hist_returns <- read.csv("C:/Users/Chris Baskerville/Documents/R_sessions and files/R_Projects/Index_Returns_Shiny/Index_returns.csv")
```
Bootstrap Sampling
```{r}
set.seed(42)
yearPickBoot <- hist_returns %>%
  select(Year) %>% 
  rep_sample_n(size = total_time, replace = TRUE, reps = reps)
```
Create simulation returns data
```{r}
sim_list <- list()
for (repl in 1:reps) {
  capital <- initial_capital
  repSet <- yearPickBoot[which(yearPickBoot$replicate == repl),]
  sim_vect <- numeric(save_time)
  #sim_vect <- numeric(total_time)
  living_expenses <- cost_of_living
  save_years_left <- save_time
  account_addition <- save_add
  
  for (obs in 1:total_time) { #Sums the changes in the account for each year 
    year <- as.numeric(repSet[obs,"Year"])
    year_return <- filter(hist_returns, Year == year)
    year_gain <-  year_return$Large_Cap*large_cap_weight*capital + year_return$Small_Cap*small_cap_weight*capital + year_return$International*international_weight*capital + year_return$Bond*bond_weight*capital + year_return$CD_Rate*CD_weight*capital
    
    if (account_for_inflation) {
      year_gain <- year_gain - year_return$Inflation * capital
    }
    
    if (account_for_inflation) {
      living_expenses <- living_expenses + living_expenses*year_return$Inflation
    }
    
    if (save_years_left > 0) {
      capital <- capital + account_addition
      account_addition <-  account_addition + save_add_increase_percent * account_addition
      save_years_left <- save_years_left - 1
    }
    
    if (save_years_left == 0) {
      capital <- capital - living_expenses
    }
    
    if (capital < 0) {
      capital <- 0
    } 
    
    sim_vect[obs] <- round(capital + year_gain)
    capital <- round(capital + year_gain)
  }
  
  sim_list[[repl]] <- sim_vect
}
sim_df <- do.call("cbind", sim_list)
colnames(sim_df) <- paste('sim', 1:reps, sep = "_")
#labels <- paste0("year", 1:save_time)
labels <- (1:total_time)
sim_df <- data.frame(cbind(sim_df, Year = labels))
```
Plots
```{r}
library(reshape2)
library(ggplot2)
library(ggthemes)
library(scales)
lot_data <- sim_df %>% 
  mutate(cur_year = Year + as.numeric(format(Sys.Date(), "%Y"))) %>% 
  select(-Year) %>%
  melt(id.vars = 'cur_year', variable.name = 'simulation') %>%
  group_by(simulation)  
  
```
Individual Simulations
```{r}
ggplot(lot_data, aes(x = cur_year, y = value)) + geom_line(aes(color = simulation)) +  scale_x_continuous(limits = c(as.numeric(format(Sys.Date(), "%Y")),total_time + as.numeric(format(Sys.Date(), "%Y"))), expand = c(0, 0)) + scale_y_continuous(labels = comma) + theme_economist() + coord_cartesian(ylim = c(0, unname(quantile(lot_data$value, 1)))) + theme(legend.position = "none") + ylab("Value of Retirement Fund ($)") + xlab('Current Year')
```
group simulations
```{r}
ggplot(lot_data, aes(x = cur_year, y = value)) + coord_cartesian(ylim = c(0, unname(quantile(lot_data$value, 0.75)))) + stat_summary(aes(y = value), fun.y = median, color="red", geom = "smooth") + theme_economist() + ylab("Value of Retirement Fund ($)") + ggtitle("Median Performance of Retirement Fund") + scale_y_continuous(labels = comma) + scale_x_continuous(name = "Year", limits = c(as.numeric(format(Sys.Date(), "%Y")),total_time + as.numeric(format(Sys.Date(), "%Y"))))
```


Histogram
```{r}
library(stats)
final_year <- sim_df %>% 
  filter(Year == total_time) %>% 
  melt(id.vars = 'Year', variable.name = 'simulation') %>% 
  arrange(desc(value))
```

```{r}
quantile(final_year$value)
```

```{r}
library(extrafont)

pct_pos <- round(100*nrow(filter(final_year, value > 0))/nrow(final_year), digits = 1)

fill <- "#4271AE"
line <- "#1F3552"

p <- ggplot(final_year, aes(x = value/100000)) +
        geom_density(fill = fill, colour = line) +
        scale_x_continuous(name = "Final Value of Retirement Fund (in $100000)") +
        scale_y_continuous(name = "Likelihood") +
        ggtitle("Chance of Completing Retirement \n with a Non-Zero Portfolio Balance") +
        theme_economist() +
        theme(legend.position = "bottom", legend.direction = "horizontal",
              legend.box = "horizontal",
              legend.key.size = unit(1, "cm"),
              plot.title = element_text(family = "Tahoma"),
              text = element_text(family = "Tahoma"),
              axis.title = element_text(size = 12),
              legend.text = element_text(size = 9),
              legend.title = element_text(face = "bold", size = 9)) + coord_cartesian(xlim = c(0, (mean(final_year$value/100000) + sd(final_year$value/100000))))

p.data <- ggplot_build(p)$data[[1]]

p.text <- lapply(split(p.data, f = p.data$group), function(df){
    df[which.max(df$scaled), ]
})

p.text <- do.call(rbind, p.text)

p + annotate('text', x = p.text$x, y = p.text$y,
             label = paste0(pct_pos, "%"), hjust = 0.2, vjust = -0.1)
  

```

```{r}
poor_mkt <- unname(quantile(final_year$value, 0.25))
avg_mkt <- unname(quantile(final_year$value, 0.5))
good_mkt <- unname(quantile(final_year$value, 0.75))
```
Create Performance Table. Can't get dplyr to find the 'value' column.
```{r}
port_perf <- lot_data %>% 
  group_by(cur_year) 
ave_perf <- summarise(port_perf, avg_perf = unname(quantile(value, 0.5)))
good_perf <- summarise(port_perf, good_perf = unname(quantile(value, 0.75)))
poor_perf <- summarise(port_perf, poor_perf = unname(quantile(value, 0.25)))

perf_table <- left_join(poor_perf, ave_perf, by = "cur_year")
perf_table <- left_join(perf_table, good_perf, by = "cur_year")
perf_table2 <- melt(perf_table, id.vars = 'cur_year', variable.name = 'performance')
levels(perf_table2$performance)[levels(perf_table2$performance) == "good_perf"] <- "Good"
levels(perf_table2$performance)[levels(perf_table2$performance) == "poor_perf"] <- "Poor"
levels(perf_table2$performance)[levels(perf_table2$performance) == "avg_perf"] <- "Average"
perf_table2$performance <-  factor(perf_table2$performance, levels = rev(levels(perf_table2$performance)))
#diamonds$cut <- factor(diamonds$cut, levels = rev(levels(diamonds$cut)))

```
Plot the three types of portfolio Performance
```{r}
ggplot(perf_table2, aes(x = cur_year, y = value, col = performance)) + geom_smooth(se = F, span = 0.2, method = 'loess', size = 1.3) + scale_x_continuous(name = "Year") + scale_y_continuous("Acount Balance") + geom_vline(xintercept = save_time + as.numeric(format(Sys.Date(), "%Y")), size = 1, colour = "#FF3721", linetype = "dashed") + theme_economist() + theme(legend.position = "right", legend.direction = "vertical",
              legend.box = "horizontal",
              legend.key.size = unit(1, "cm"),
              plot.title = element_text(family = "Tahoma"),
              text = element_text(family = "Tahoma"),
              axis.title = element_text(size = 12),
              legend.text = element_text(size = 9),
              legend.title = element_text(face = "bold", size = 9)) + annotate('text', x = save_time + as.numeric(format(Sys.Date(), "%Y")), y = max(good_perf), label = "Retirement", hjust = 0.9, vjust = 1, angle = 90)

#Value of portfolio based on market Performance.
```
